apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-cluster-configuration
spec:
  interval: 1h0m0s
  releaseName: nginxingress-ingress-nginx-controller
  targetNamespace: ingress-nginx
  storageNamespace: ingress-nginx
  timeout: 10m0s
  chart:
    spec:
      chart: ingress-nginx
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  values:
    controller:
      watchIngressWithoutClass: true
      ingressClassResource:
        default: true
      config:
        server-tokens: "false"
      ingressClass: nginx
      service:
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
      extraArgs:
        default-ssl-certificate: default/azingressdesa-cert
        enable-ssl-chain-completion: false
        enable-ssl-passthrough: true
      resources:
        requests:
          cpu: 100m
          memory: 300Mi
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 5
        targetCPUUtilizationPercentage: 100
        targetMemoryUtilizationPercentage: 200
      nodeSelector:
        kubernetes.azure.com/mode: system
    defaultBackend:
      nodeSelector.kubernetes.io/os: linux